site_name: Ra2 SuperHero Redson V2.0
nav:
- Eng:
    About: eng/about.md
    Index: eng/index.md
- Vi:
    Index: vi/index.md
extra:
  alternate:
    - name: "ğŸ‡»ğŸ‡³ Tiáº¿ng Viá»‡t"
    link: /vi/
    lang: vi
    - name: "ğŸ‡¬ğŸ‡§ English"
    link: /en/
    lang: en
theme:
  name: material
palette:
    - scheme: default  # Cháº¿ Ä‘á»™ sÃ¡ng máº·c Ä‘á»‹nh
      toggle:
        icon: material/weather-night  # Icon máº·t trÄƒng
        name: Chuyá»ƒn sang cháº¿ Ä‘á»™ tá»‘i
    - scheme: slate  # Cháº¿ Ä‘á»™ tá»‘i
      toggle:
        icon: material/weather-sunny  # Icon máº·t trá»i
        name: Chuyá»ƒn sang cháº¿ Ä‘á»™ sÃ¡ng
        
