site_name: Ra2 SuperHero Redson V2.0
nav:
  - SKIRNISH MODE:
    - Gi·ªõi Thi·ªáu: index.md
    - C√≥ g√¨ m·ªõi ?: NEWS.md
    - Si√™u Anh H√πng:
      - Phe ƒê·ªìng Minh: HEROALLIED.md
      - Phe Soviet: HEROSOVIET.md
      - Phe Yuri: HEROYURI.md
      - Phe Asian: HEROASIAN.md
      - ƒê·∫∑c Bi·ªát: HEROSPECIAL.md
    - Si√™u Ng∆∞·ªùi M√°y:
      - Phe ƒê·ªìng Minh: EPICALLIED.md
      - Phe Soviet: EPICSOVIET.md
      - Phe Yuri: EPICYURI.md
      - Phe Asian: EPICASIAN.md
    - Tr·ª• Si√™u C·∫•p: SOLAMER.md
    - Si√™u V≈© Kh√≠ Ch√≠nh: SW.md
    - Si√™u V≈© Kh√≠ Ph·ª•: SWMINI.md
    - ƒê·ªânh Olympus: Olympus.md
    - H∆∞·ªõng D·∫´n Client: CLIENT.md
    - Th√¥ng Tin T√°c Gi·∫£: INFO.md
    - Youtube: https://www.youtube.com/@mr.solobdu
    - DONATE: DONATE.md
  - CAMPAIGN MODE:
    - Gi·ªõi Thi·ªáu: index2.md
    - C√≥ g√¨ m·ªõi ?: NEWS2.md
    - H∆∞·ªõng D·∫´n Chi·∫øn D·ªãch:
      - G·ªëc ƒê·ªìng Minh: MSORGINALAL.MD
      - G·ªëc Soviet: MSORGINALSV.MD
      - T√°i Kh·ªüi ƒê·ªông ƒê·ªìng Minh: MSREALLIED.MD
      - T√°i Kh·ªüi ƒê·ªông Soviet: MSRESOVIET.MD
      - G·ªëc Yuri: MSORGINALYR.MD
      - Yuri B√°o Th√π: MSYURIRE.MD
      - L√∫c B√¨nh Minh: MSALERTDAWN.MD
      - L√∫c H·ª´ng ƒê√¥ng: MSALERTSUN.MD
      - Soviet M·ªü R·ªông: MSNEWSOVIET.MD
      - Yuri M·ªü R·ªông: MSNEWYURI.MD
    - Th√¥ng Tin T√°c Gi·∫£: INFO2.md
    - Youtube: https://www.youtube.com/@mr.solobdu
    - DONATE: DONATE2.md
extra:
  alternate:
    - name: üáªüá≥ Ti·∫øng Vi·ªát
      link: /
      lang: vi
      class: lang-switch
    - name: üá¨üáß English
      link: /eng/
      lang: en
      class: lang-switch
extra_javascript:
  - javascripts/custom.js
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  language: vi 
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Chuy·ªÉn sang ch·∫ø ƒë·ªô t·ªëi
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Chuy·ªÉn sang ch·∫ø ƒë·ªô s√°ng
