site_name: Ra2 SuperHero Redson V2.0
nav:
  - Giá»›i Thiá»‡u: index.md
  - CÃ³ gÃ¬ má»›i ?: NEWS.md
  - SiÃªu Anh HÃ¹ng:
    - Phe Äá»“ng Minh: HEROALLIED.md
    - Phe Soviet: HEROSOVIET.md
    - Phe Yuri: HEROYURI.md
    - Phe Asian: HEROASIAN.md
    - Äáº·c Biá»‡t: HEROSPECIAL.md
  - SiÃªu NgÆ°á»i MÃ¡y:
    - Phe Äá»“ng Minh: EPICALLIED.md
    - Phe Soviet: EPICSOVIET.md
    - Phe Yuri: EPICYURI.md
    - Phe Asian: EPICASIAN.md
  - Trá»¥ SiÃªu Cáº¥p: SOLAMER.md
  - SiÃªu VÅ© KhÃ­ ChÃ­nh: SW.md
  - SiÃªu VÅ© KhÃ­ Phá»¥: SWMINI.md
  - Äá»‰nh Olympus: Olympus.md
  - HÆ°á»›ng Dáº«n Client: CLIENT.md
  - ThÃ´ng Tin TÃ¡c Giáº£: INFO.md
  - Youtube: https://www.youtube.com/@mr.solobdu
  - DONATE: DONATE.md
extra:
  alternate:
    - name: ğŸ‡»ğŸ‡³ Tiáº¿ng Viá»‡t
      link: /
      lang: vi
      class: lang-switch
    - name: ğŸ‡¬ğŸ‡§ English
      link: /eng/
      lang: en
      class: lang-switch
theme:
  language: vi 
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Chuyá»ƒn sang cháº¿ Ä‘á»™ tá»‘i
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Chuyá»ƒn sang cháº¿ Ä‘á»™ sÃ¡ng
