site_name: Ra2 SuperHero Redson V2.0
nav:
  - Skirmish Version:
    - Giá»›i Thiá»‡u: index.md
    - CÃ³ gÃ¬ má»›i ?: NEWS.md
    - SiÃªu Anh HÃ¹ng:
      - Phe Äá»“ng Minh: HEROALLIED.md
      - Phe Soviet: HEROSOVIET.md
      - Phe Yuri: HEROYURI.md
      - Phe Asian: HEROASIAN.md
      - Äáº·c Biá»‡t: HEROSPECIAL.md
    - SiÃªu NgÆ°á»i MÃ¡y:
      - Phe Äá»“ng Minh: EPICALLIED.md
      - Phe Soviet: EPICSOVIET.md
      - Phe Yuri: EPICYURI.md
      - Phe Asian: EPICASIAN.md
    - Trá»¥ SiÃªu Cáº¥p: SOLAMER.md
    - SiÃªu VÅ© KhÃ­ ChÃ­nh: SW.md
    - SiÃªu VÅ© KhÃ­ Phá»¥: SWMINI.md
    - Äá»‰nh Olympus: Olympus.md
    - HÆ°á»›ng Dáº«n Client: CLIENT.md
    - ThÃ´ng Tin TÃ¡c Giáº£: INFO.md
    - Youtube: https://www.youtube.com/@mr.solobdu
    - DONATE: DONATE.md
  - Campaign Version:
    - Giá»›i Thiá»‡u: index2.md
    - CÃ³ gÃ¬ má»›i ?: NEWS2.md
    - HÆ°á»›ng Dáº«n Chiáº¿n Dá»‹ch:
      - Gá»‘c Äá»“ng Minh: MSORGINALAL.md
      - Gá»‘c Soviet: MSORGINALSV.md
      - TÃ¡i Khá»Ÿi Äá»™ng Äá»“ng Minh: MSREALLIED.md
      - TÃ¡i Khá»Ÿi Äá»™ng Soviet: MSRESOVIET.md
      - Gá»‘c Yuri (Äá»“ng Minh): MSORGINALYRAL.md
      - Gá»‘c Yuri (Soviet): MSORGINALYRSV.md
      - Yuri BÃ¡o ThÃ¹: MSYURIRE.md
      - LÃºc BÃ¬nh Minh: MSALERTDAWN.md
      - LÃºc Há»«ng ÄÃ´ng: MSALERTSUN.md
      - Soviet Má»Ÿ Rá»™ng: MSNEWSOVIET.md
      - Yuri Má»Ÿ Rá»™ng: MSNEWYURI.md
    - ThÃ´ng Tin TÃ¡c Giáº£: INFO2.md
    - Youtube: https://www.youtube.com/@mr.solobdu
    - DONATE: DONATE2.md
extra:
  alternate:
    - name: ğŸ‡»ğŸ‡³ Tiáº¿ng Viá»‡t
      link: /
      lang: vi
      class: lang-switch
    - name: ğŸ‡¬ğŸ‡§ English
      link: /eng/
      lang: en
      class: lang-switch
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/custom.js
theme:
  logo: logo.png
  favicon: assets/favicon.ico
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  language: vi 
  name: material
  palette:
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Chuyá»ƒn sang cháº¿ Ä‘á»™ tá»‘i
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Chuyá»ƒn sang cháº¿ Ä‘á»™ sÃ¡ng
