site_name: Ra2 SuperHero Redson V2.0
nav:
- Eng:
    About: eng/about.md
    Index: eng/index.md
- Vi:
    Index: vi/index.md
    Infovi: vi/infovi.md
extra:
  alternate:
  - name: ðŸ‡»ðŸ‡³ Tiáº¿ng Viá»‡t
    link: /vi/
    lang: vi
  - name: ðŸ‡¬ðŸ‡§ English
    link: /en/
    lang: en
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Chuyá»ƒn sang cháº¿ Ä‘á»™ tá»‘i
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Chuyá»ƒn sang cháº¿ Ä‘á»™ sÃ¡ng
